packages:
  - 'backend'
  - 'frontend'
  - 'extension'
  - 'worker'
  - 'packages/contracts'

allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@parcel/watcher': true
  'prisma': true
  'esbuild': true
  'playwright': true
  'sharp': true
  'lmdb': true
  'msgpackr-extract': true
  'unrs-resolver': true
  better-sqlite3: true
  bcrypt: true
  'class-transformer': true
  'class-validator': true
  '@scarf/scarf': true
